# Generated by Django 3.2.8 on 2021-12-16 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_result_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 9, 48, 34, 953429)),
        ),
    ]
